"use strict";
let x = 10;
console.log(x);
console.log(typeof (x));
const y = 3.145123;
console.log(y);
console.log(typeof (y));
console.log(y.toPrecision(3));
const firstName = "Foo";
console.log(firstName);
console.log(typeof (firstName));
let fullName = "Foo Bar";
console.log(fullName);
fullName = firstName + " " + fullName;
console.log(fullName);
const isSomething = true;
console.log(isSomething);
console.log(typeof (isSomething));
